genrand.height=8
genrand.width=8
genrand.treenum=4
genrand.tanknum=8
genfile.fpath=src/main/resources/level.txt

map.levelConfigFileName=level.tmx
map.tankTextureFile=images/tank_blue.png
map.treeTextureFile=images/greenTree.png
map.bulletTexture=images/bullet.png
